language: python
python:
  - "2.6"
  - "2.7"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq lame flac
 - sudo rmdir /dev/shm
 - sudo ln -Tsf /{run,dev}/shm
install: "pip install -r requirements.txt"
script: nosetests
