language: python
python:
  - "3.8"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq lame flac
 - sudo rmdir /dev/shm
 - sudo ln -Tsf /{run,dev}/shm
install: 'pip install -e ".dev"'
script: nosetests
